# Generated by Django 3.0.7 on 2020-07-10 05:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200706_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='date_joined',
            field=models.DateField(default=datetime.datetime(2020, 7, 10, 5, 3, 41, 593179, tzinfo=utc)),
        ),
    ]
