# Generated by Django 3.0.7 on 2020-07-10 05:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200710_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='commentsCnt',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='likesCnt',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='references',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='date_joined',
            field=models.DateField(default=datetime.datetime(2020, 7, 10, 5, 6, 22, 800356, tzinfo=utc)),
        ),
    ]
