# Generated by Django 3.0.7 on 2020-07-10 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200710_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='followers',
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'get_latest_by': ['-date_time'], 'ordering': ['-likesCnt', '-date_time']},
        ),
        migrations.AddField(
            model_name='article',
            name='dislikesCnt',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Follower',
        ),
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
