# Generated by Django 3.0.7 on 2020-07-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200712_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='isPublished',
            field=models.BooleanField(default=True),
        ),
    ]
