# Generated by Django 3.0.7 on 2020-07-12 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_article_ispublished'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'get_latest_by': ['-date_time'], 'ordering': ['-date_time', '-likesCnt']},
        ),
    ]
