# Generated by Django 3.0.7 on 2020-07-18 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200712_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='type',
            field=models.BooleanField(default=True),
        ),
    ]
